### ISSUE TITLE
Is ranlib converted to Matlab?

### ISSUE THREAD

**Issue by ZhouChuanyou** [tnakaicode/jburkardt-python#1]
Dear Sir,
      Nice to get your Python version of ranlib. That's a great work! Have you converted it to Matlab? Or do you know who have finished this task? 
      My email: 201772258@yangtzeu.edu.cn
      Look forward to hearing from you!

Best wishes!
Zhou Chuanyou

**Comment by tnakaicode** [comment]
This is not my job. I got this URL; https://people.sc.fsu.edu/~jburkardt/py_src/py_src.html . 
You can get MATLAB code from https://people.sc.fsu.edu/~jburkardt/py_src/m_src.html .
